### PR TITLE
Feat/url compatibility

### PR DESCRIPTION
**Pull request by mariomurrent-softwaresolutions**
PR to #1 

I just added the url-parse package in order to be compatible with previous node versions <= 20

### CODE REVIEW

**Review by ibc — APPROVED** [review]

**Comment by mariomurrent-softwaresolutions** [comment]
Thx for approval - are you releasing a new version?

**Comment by ibc** [comment]
Unfortunately I am not maintaining/releasing this library anymore and honestly I don't have time for it. I suggest using `git+ssh` URLs in your package.json pointing to latest commit.

**Comment by mariomurrent-softwaresolutions** [comment]
Alright

**Comment by mariomurrent-softwaresolutions** [comment]
I can release it as well under a new package name?

**Comment by ibc** [comment]
You can fork and release as you wish, of course

**Pull request merged**
